version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    expose:
      - 900
    runtime: nvidia   # Add this line to specify the NVIDIA runtime
      environment:
        - NVIDIA_VISIBLE_DEVICES=all   # Optionally, specify which GPUs to use
        - NVIDIA_DRIVER_CAPABILITIES=all  # Make sure all required capabilities are available

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:1234"