version: "3.8"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    expose:
      - 5000:900
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:1234"